services:
  db:
    image: bitnami/postgresql:15.3.0
    ports:
      - 5432:5432
    volumes:
      - join_investigation_db:/bitnami/postgresql
      - ../db/dump:/home/dump
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=test_gem
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    # restart: always
    networks:
      - net_db
      - net_investigation

  db_flyway:
    image: flyway/flyway:9.18-alpine
    volumes:
      - ../db/db_versioning/flyway_conf:/flyway/conf
      - ../db/db_versioning/sql:/flyway/sql
    command: -connectRetries=60 migrate
    # command: -connectRetries=60 migrate && cp /flyway/report.html /flyway/conf/report.html
    depends_on:
      - db
    networks:
      - net_db

  socket_server:
    image: node:22.15.0-alpine3.21
    # environment:
    #   - VAR1=5000
    #   - VAR2=/models/tfjs_model
    working_dir: /home
    command: ["npm", "run", "dev"]
    depends_on:
      - db
    volumes:
      - ../socket-server:/home
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_NAME=test_gem
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - FRONTEND_URL=http://localhost:3000
    networks:
      - net_db

  # nginx:
  #   # build: ../nginx
  #   image: nginx:alpine
  #   # ports:
  #   #   - 80:80
  #   # restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-file: "5"
  #       max-size: "20m"
  #   depends_on:
  #     - socket_server
  #   network_mode: "host"

volumes:
  join_investigation_db:
    external: true

networks:
  net_db:
    external: false


  net_investigation:
    external: true
# docker volume create --name=join_investigation_db
# docker network create net_investigation
