FROM node:22.15.0-alpine3.21 AS base

# Install dependencies only when needed
FROM base AS deps

WORKDIR /app
COPY package.json .
# install dependencies
RUN npm install


# Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# build
RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static


ENV PORT=3000

EXPOSE 3000

CMD ["node", "server.js"]
