FROM maven:3.9.9-amazoncorretto-21-alpine AS build
LABEL stage=builder

WORKDIR /project
COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
ENV TZ=Asia/Seoul
WORKDIR /app
COPY --from=build /project/target/nfteyes-0.0.1-SNAPSHOT.jar /app/app.jar

CMD ["java", "-jar", "app.jar"]
