export const tableColumns = [
  { key: "no", title: "No.", textAlign: "text-center" },
  { key: "title", title: "제목", textAlign: "text-left" },
  { key: "date", title: "날짜", textAlign: "text-center" },
  { key: "viewers", title: "조회수", textAlign: "text-center" },
  { key: "attachedFile", title: "첨부파일", textAlign: "text-center" },
];
export const tableData = [
  {
    no: 130,
    title: "해외 스트리밍 사이트 통한 저작권 침해 사례 공유",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 129,
    title: "○○ 플랫폼 내 불법 영상 업로드 계정 추적 정보",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 128,
    title: "최근 적발된 웹툰 불법 유통 경로 분석",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 127,
    title: "음악 파일 불법 공유 커뮤니티 목록 및 활동 패턴",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 126,
    title: "다국적 P2P 사이트 통한 저작물 유통 정황 제보",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 125,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 124,
    title: "인터폴 협력 사례 공유 세미나 참가 신청 안내",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 123,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 122,
    title: "인터폴 협력 사례 공유 세미나 참가 신청 안내",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 121,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
];
