export const tableColumns = [
  { key: "no", title: "No.", textAlign: "text-center" },
  { key: "title", title: "제목", textAlign: "text-left" },
  { key: "date", title: "날짜", textAlign: "text-center" },
  { key: "viewers", title: "조회수", textAlign: "text-center" },
  { key: "attachedFile", title: "첨부파일", textAlign: "text-center" },
];
export const tableData = [
  {
    no: 35,
    title: "인터폴 협력 사례 공유 세미나 참가 신청 안내",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 34,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 33,
    title: "인터폴 협력 사례 공유 세미나 참가 신청 안내",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 32,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 31,
    title: "인터폴 협력 사례 공유 세미나 참가 신청 안내",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 30,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 29,
    title: "인터폴 협력 사례 공유 세미나 참가 신청 안내",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 28,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
  {
    no: 27,
    title: "인터폴 협력 사례 공유 세미나 참가 신청 안내",
    date: "2024.05.19",
    viewers: 64,
    attachedFile: 1,
  },
  {
    no: 26,
    title: "2025 상반기 국제공조수사 워크샵 개최 안내",
    date: "2024.05.11",
    viewers: 125,
    attachedFile: 0,
  },
];
