export const tableColumns = [
  { key: "caseNumber", title: "사건번호" },
  { key: "name", title: "사건 명" },
  { key: "representative", title: "담당자" },
  { key: "country", title: "발생국가" },
  { key: "startDate", title: "수사 시작일" },
  { key: "infringementType", title: "침해유형" },
  { key: "state", title: "상태" },
  { key: "status", title: "상세 진행 현황" },
];

export const tableData = [
  {
    id: 1,
    caseNumber: 156,
    name: "test2",
    representative: "test3",
    country: "test4",
    startDate: "test5",
    infringementType: "test6",
    status: "test8",
  },
  {
    id: 2,
    caseNumber: 411,
    name: "test22",
    representative: "test33",
    country: "test44",
    startDate: "test55",
    infringementType: "test66",
    status: "test88",
  },
  {
    id: 3,
    caseNumber: 893,
    name: "test222",
    representative: "test333",
    country: "test444",
    startDate: "test555",
    infringementType: "test666",
    status: "test888",
  },
  {
    id: 4,
    caseNumber: 456,
    name: "2222",
    representative: "3333",
    country: "4444",
    startDate: "5555",
    infringementType: "6666",
    status: "8888",
  },
];
