const Dashboard = ({ color = "#C3C3C3" }) => (
  <svg
    width="18"
    height="18"
    viewBox="0 0 18 18"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="1"
      y="1"
      width="6"
      height="6"
      rx="1"
      stroke={color}
      strokeWidth="2"
      strokeLinejoin="round"
    />
    <rect
      x="1"
      y="11"
      width="6"
      height="6"
      rx="1"
      stroke={color}
      strokeWidth="2"
      strokeLinejoin="round"
    />
    <rect
      x="11"
      y="11"
      width="6"
      height="6"
      rx="1"
      stroke={color}
      strokeWidth="2"
      strokeLinejoin="round"
    />
    <rect
      x="11"
      y="1"
      width="6"
      height="6"
      rx="1"
      stroke={color}
      strokeWidth="2"
      strokeLinejoin="round"
    />
  </svg>
);
export default Dashboard;
