export const PROGRESS_STATUS = {
  PRE_INVESTIGATION: 'PRE_INVESTIGATION',
  INVESTIGATION: 'INVESTIGATION',
  TRANSFER: 'TRANSFER',
  ANALYZING: 'ANALYZING',
  REPORT_INVESTIGATION: 'REPORT_INVESTIGATION',
  DISPOSE: 'DISPOSE',
  ON_HOLD: 'ON_HOLD',
};

export const REVIEW_STATUS = {
  WRITING: 'WRITING',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const DEFAULT_PAGE_SIZE = 10;
