export const PROGRESS_STATUS = {
  PRE_INVESTIGATION: 'PRE_INVESTIGATION',
  INVESTIGATION: 'INVESTIGATION',
  REVIEW: 'REVIEW',
  PROSECUTION: 'PROSECUTION',
  CLOSED: 'CLOSED'
};

export const DEFAULT_PAGE_SIZE = 10;
